export default {
  nav: { howItWorks: "Cómo funciona", mcp: "MCP", telegram: "Telegram", continueWithGithub: "Continuar con GitHub" },
  footer: { start: "Empezar" },
  commits: { eyebrow: "Ingesta de commits · Dominios", title: "Cada commit se clasifica solo, sin que nadie tenga que opinar sobre el avance.", description: "Define los dominios de tu proyecto — los que tú quieras, no una taxonomía impuesta. Pemie clasifica la ingesta automáticamente y el avance por dominio se calcula solo.", messages: { "a41f2c9": "auth: refresh tokens", "7d03be1": "ci: build cache", "c9e0d12": "kanban: drag by column", "e12aa04": "etl: domains v2" } },
  dualSurface: { eyebrow: "Dos superficies, un dato", title: "Lo que ve tu equipo es lo que lee tu agente.", peopleLabel: "personas · app web", peopleTitle: "Para quien pregunta \"¿cómo vamos?\"", peopleBullets: ["Objetivo e informes de avance por dominio", "Historias de usuario y Kanban", "Ingesta de commits clasificada y navegable"], agentsLabel: "agentes · MCP sobre HTTP", agentsTitle: "Para quien ejecuta el trabajo", agentBullets: ["Tools sobre los mismos datos: informes, HUs, commits", "API keys con scopes por proyecto", "Audit log de cada llamada"] },
  finalCta: { title: "Conecta tu primer repo y que cada \"¿cómo vamos?\" lo conteste un commit.", description: "En minutos estarás viendo tu primer informe, sin migraciones ni ceremonia.", start: "Empezar", continueWithGithub: "Continuar con GitHub" },
  howItWorks: { eyebrow: "Cómo funciona", title: "De cero a una fuente de verdad en cuatro pasos.", steps: [{ title: "Workspace", description: "Crea tu workspace, invita al equipo y organiza varios proyectos en un solo lugar." }, { title: "Proyecto", description: "Define el objetivo del proyecto y los dominios que te importan: api, infra, ui, datos." }, { title: "GitHub", description: "Conecta el repo. Pemie ingiere los commits y los clasifica por dominio, sin trabajo manual." }, { title: "Agente", description: "Genera una API key con scopes. Cursor, Hermes o Telegram trabajan sobre la misma verdad." }], videoLabel: "app.pemie.ai · conectar agente", videoCaption: "demo real · conectar Hermes con pemie", videoAriaLabel: "Video tutorial: cómo conectar Hermes con pemie, paso a paso" },
  telegram: { channelLabel: "canal telegram · {{project}}", question: "¿Cómo vamos con {{project}} esta semana?", answer: "Avance 74% (+6 pts). Se cerró auth con refresh tokens y CI con cache de builds. 3 HUs pasaron a hecho.", evidence: "evidencia: a41f2c9 · 7d03be1 · c9e0d12", scope: "respondido con tu key · scope reports:read", eyebrow: "Canal Telegram · BYOK", title: "El proyecto responde tus preguntas en Telegram.", description: "Trae tu propia key — Anthropic, OpenAI o DeepSeek — y el canal responde con datos del proyecto, con los scopes que tú definas. Tu modelo, tus límites, tu factura." },
} as const;
