export default {
  nav: { howItWorks: "How it works", mcp: "MCP", telegram: "Telegram", continueWithGithub: "Continue with GitHub" },
  footer: { start: "Get started" },
  commits: { eyebrow: "Commit ingestion · Domains", title: "Every commit classifies itself, without anyone having to weigh in on progress.", description: "Define your project's domains — whatever you want, not an imposed taxonomy. Pemie classifies ingestion automatically and calculates progress by domain for you.", messages: { "a41f2c9": "auth: refresh tokens", "7d03be1": "ci: build cache", "c9e0d12": "kanban: drag by column", "e12aa04": "etl: domains v2" } },
  dualSurface: { eyebrow: "Two surfaces, one data source", title: "What your team sees is what your agent reads.", peopleLabel: "people · web app", peopleTitle: "For whoever asks \"how are we doing?\"", peopleBullets: ["Project goals and progress reports by domain", "User stories and Kanban", "Classified, browsable commit ingestion"], agentsLabel: "agents · MCP over HTTP", agentsTitle: "For whoever does the work", agentBullets: ["Tools over the same data: reports, stories, commits", "API keys scoped by project", "Audit log for every call"] },
  finalCta: { title: "Connect your first repo and let every \"how are we doing?\" be answered by a commit.", description: "You will be seeing your first report in minutes, with no migrations or ceremony.", start: "Get started", continueWithGithub: "Continue with GitHub" },
  howItWorks: { eyebrow: "How it works", title: "From zero to a source of truth in four steps.", steps: [{ title: "Workspace", description: "Create your workspace, invite your team, and organize multiple projects in one place." }, { title: "Project", description: "Define the project's goal and the domains that matter to you: api, infra, ui, data." }, { title: "GitHub", description: "Connect the repo. Pemie ingests commits and classifies them by domain, with no manual work." }, { title: "Agent", description: "Generate an API key with scopes. Cursor, Hermes, or Telegram work from the same source of truth." }], videoLabel: "app.pemie.ai · connect agent", videoCaption: "real demo · connect Hermes to pemie", videoAriaLabel: "Tutorial video: how to connect Hermes to pemie, step by step" },
  telegram: { channelLabel: "telegram channel · {{project}}", question: "How are we doing with {{project}} this week?", answer: "Progress 74% (+6 pts). Auth with refresh tokens and CI with build cache were completed. 3 stories moved to done.", evidence: "evidence: a41f2c9 · 7d03be1 · c9e0d12", scope: "answered with your key · scope reports:read", eyebrow: "Telegram channel · BYOK", title: "Your project answers your questions in Telegram.", description: "Bring your own key — Anthropic, OpenAI, or DeepSeek — and the channel answers with project data and the scopes you define. Your model, your limits, your bill." },
} as const;
