// Catálogo de codes usados hoy como argumento explícito en `badRequest`/`conflict`
// (greppeados de los call sites reales). Los defaults de `forbidden`/`notFound`/
// `unauthorized` sin code propio quedan fuera: eso lo resuelve B3.

export const ERROR_CODES = [
  "invalid_body",
  "invalid_locale",
  "invalid_email",
  "weak_password",
  "email_taken",
  "empty_body",
  "unsupported_content_type",
  "missing_installation",
  "github_not_connected",
  "invalid_repo",
  "repo_exists",
  "github_token_expired",
  "duplicate_keys",
  "empty_fallback",
  "empty_title",
  "invalid_type",
  "invalid_column",
  "story_mismatch",
  "story_has_card",
  "epic_cannot_have_card",
  "invalid_slug",
  "invalid_name",
  "invalid_description",
  "invalid_path",
  "file_too_large",
  "too_many_files",
  "skill_too_large",
  "empty_files",
  "missing_skill_md",
  "invalid_target",
  "invalid_destination",
  "upload_expired",
  "download_expired",
  "invalid_title",
  "invalid_priority",
  "invalid_status",
  "invalid_json_field",
  "epic_mismatch",
  "epic_cannot_have_epic",
  "not_an_epic",
  "epic_has_children",
  "epic_has_no_points",
  "epic_cannot_have_card",
  "key_collision",
  "placeholder_email",
  "invalid_role",
  "already_member",
  "invite_expired",
  "invalid_objective",
  "invalid_date",
  "invalid_score",
  "empty_note",
  "empty_response",
  "report_mismatch",
  "unsafe_tar_entry",
  "invalid_archive",
  "invalid_llm_provider",
  "invalid_llm_key",
  "telegram_not_configured",
  "invalid_link_token",
  "link_token_expired",
  "invalid_model",
  "provider_key_missing",
  "assignee_mismatch",
  "invalid_scope_level",
  "no_scopes",
  "invalid_scopes",
  "project_required",
  "project_mismatch",
  "agent_mismatch",
  "scope_mismatch",
  "project_id_required",
  "workspace_id_required",
  "unknown_tool",
  "query_too_short",
  "secrets_key_missing",
  "secrets_key_invalid",
  "bad_ciphertext",
  // B3a — tenancy.ts + auth.ts (forbidden/notFound/unauthorized sin code propio).
  "workspace_not_found",
  "insufficient_workspace_role",
  "name_too_short",
  "member_not_found",
  "cannot_change_owner_role",
  "cannot_remove_owner",
  "cannot_remove_self",
  "invalid_invite_role",
  "invitation_not_found",
  "invalid_invitation",
  "user_not_found",
  "invitation_email_mismatch",
  "project_not_found",
  "invalid_credentials",
  // B3b — agents.ts (forbidden/notFound/unauthorized sin code propio).
  "agent_name_too_short",
  "agent_not_found",
  "api_key_name_too_short",
  "user_key_not_workspace_scoped",
  "not_personal_key_owner",
  "api_key_not_found",
  "invalid_api_key",
  "api_key_expired",
  "api_key_missing_scope",
  "agent_presence_blocked",
  "agent_presence_not_found",
  "api_key_no_project",
  "api_key_project_pinned",
  "project_not_in_key_workspace",
  "api_key_no_owner",
  "key_owner_not_member",
  "key_owner_not_workspace_member",
  "write_scope_requires_member",
  "read_scope_requires_viewer",
  "api_key_no_workspace",
  "api_key_workspace_pinned",
  "workspace_not_accessible",
  // B3c — stories.ts + board.ts + assignees.ts (forbidden/notFound/unauthorized sin code propio).
  "story_title_too_short",
  "story_not_found",
  "contributor_not_found",
  "card_not_found",
  "invalid_target_column",
  "card_update_title_empty",
  // B3d — skills.ts + skill-archive.ts + reports.ts + ingest.ts + channels.ts + search.ts + stats.ts.
  "duplicate_path",
  "skill_not_found",
  "unsafe_skill_path",
  "upload_ticket_not_found",
  "download_token_not_found",
  "report_not_found",
  "note_not_found",
  "repo_not_found",
  "installation_not_linked",
  "github_repo_forbidden",
  "github_repo_not_found",
  "invalid_anthropic_key",
  "invalid_openai_key",
  "not_workspace_member",
  // B3e — rest/**, mcp/index.ts, lib/secrets.ts (última tanda: cierra la migración).
  "invalid_login_body",
  "invalid_preference_body",
  "invalid_request_body",
  "invalid_llm_key_body",
  "not_authenticated",
  "invalid_workspace_name",
  "invalid_member_role",
  "invalid_invitation_body",
  "invalid_project_body",
  "invalid_repo_body",
  "invalid_domain_config",
  "invalid_objective_body",
  "invalid_report_body",
  "invalid_note_body",
  "invalid_answer_body",
  "invalid_agent_body",
  "invalid_api_key_body",
  "invalid_contributor_body",
  "invalid_story_body",
  "invalid_card_body",
  "invalid_move_body",
  "invalid_skill_body",
  "invalid_keep_card",
  "invalid_target_list",
  "invalid_destination_list",
  "note_not_in_project",
  "story_not_in_project",
  "card_not_in_project",
  "no_read_scope_for_search",
  "api_key_missing_permission",
  // B6 — webhooks entrantes (rest/webhooks.ts): eran texto en español suelto,
  // fuera de sessionMiddleware. Se renderizan en el locale default ("es").
  "invalid_webhook_signature",
  "invalid_webhook_payload",
  "invalid_telegram_secret",
  // PEM-56 — los límites sostienen que la actividad sea legible y que el TTL
  // siga siendo una señal útil, no un mecanismo de presencia permanente.
  "invalid_activity_summary",
  "invalid_activity_state",
  "invalid_activity_interval",
  "invalid_activity_path",
  // Modo mesa: errores de dominio estables para REST y futuros bordes MCP.
  "brainstorm_session_not_found",
  "brainstorm_node_not_found",
  "brainstorm_contributor_mismatch",
  "brainstorm_session_not_recording",
  "invalid_brainstorm_title",
  "invalid_brainstorm_segment",
  "invalid_brainstorm_speaker",
  "invalid_brainstorm_node",
  "invalid_brainstorm_audio",
  "invalid_brainstorm_body",
  "invalid_brainstorm_recorder_token",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

/** Bolsa de interpolación para codes con `${...}` en su texto original. */
export type ErrorParams = Record<string, string | number>;
